apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: fks4py9j3-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fks4py9j3-go 
  name: fks4py9j3-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: fks4py9j3-go 
