apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: fks4py9j3-go 
  janus-idp.io/tekton: fks4py9j3-go
  backstage.io/kubernetes-id: fks4py9j3-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: fks4py9j3-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml